CREATE TABLE IF NOT EXISTS users_for_delete AS SELECT * FROM Users WHERE 1=0;
CREATE TABLE IF NOT EXISTS posts_for_delete AS SELECT * FROM Posts WHERE 1=0;
CREATE TABLE IF NOT EXISTS badges_for_delete AS SELECT * FROM Badges WHERE 1=0;
CREATE TABLE IF NOT EXISTS comments_for_delete AS SELECT * FROM Comments WHERE 1=0;
CREATE TABLE IF NOT EXISTS posttypes_for_delete AS SELECT * FROM PostTypes WHERE 1=0;
CREATE TABLE IF NOT EXISTS linktypes_for_delete AS SELECT * FROM LinkTypes WHERE 1=0;
CREATE TABLE IF NOT EXISTS postlinks_for_delete AS SELECT * FROM PostLinks WHERE 1=0;
CREATE TABLE IF NOT EXISTS votetypes_for_delete AS SELECT * FROM VoteTypes WHERE 1=0;
CREATE TABLE IF NOT EXISTS votes_for_delete AS SELECT * FROM Votes WHERE 1=0;

INSERT INTO users_for_delete SELECT * FROM Users ON CONFLICT DO NOTHING;
INSERT INTO posts_for_delete SELECT * FROM Posts ON CONFLICT DO NOTHING;
INSERT INTO badges_for_delete SELECT * FROM Badges ON CONFLICT DO NOTHING;
INSERT INTO comments_for_delete SELECT * FROM Comments ON CONFLICT DO NOTHING;
INSERT INTO posttypes_for_delete SELECT * FROM PostTypes ON CONFLICT DO NOTHING;
INSERT INTO linktypes_for_delete SELECT * FROM LinkTypes ON CONFLICT DO NOTHING;
INSERT INTO postlinks_for_delete SELECT * FROM PostLinks ON CONFLICT DO NOTHING;
INSERT INTO votetypes_for_delete SELECT * FROM VoteTypes ON CONFLICT DO NOTHING;
INSERT INTO votes_for_delete SELECT * FROM Votes ON CONFLICT DO NOTHING;