-- Hash indexes nao ideais para com_like (MySQL)
CREATE INDEX idx_users_id_hash_extra ON Users (Id) USING HASH;
CREATE INDEX idx_posts_id_hash_extra ON Posts (Id) USING HASH;
CREATE INDEX idx_badges_id_hash_extra ON Badges (Id) USING HASH;
CREATE INDEX idx_comments_id_hash_extra ON Comments (Id) USING HASH;
CREATE INDEX idx_posttypes_id_hash_extra ON PostTypes (Id) USING HASH;
CREATE INDEX idx_linktypes_id_hash_extra ON LinkTypes (Id) USING HASH;
CREATE INDEX idx_postlinks_id_hash_extra ON PostLinks (Id) USING HASH;
CREATE INDEX idx_votetypes_id_hash_extra ON VoteTypes (Id) USING HASH;
CREATE INDEX idx_votes_id_hash_extra ON Votes (Id) USING HASH;
