DROP INDEX idx_users_displayname_hash ON Users;
DROP INDEX idx_posts_body_hash ON Posts;
DROP INDEX idx_badges_name_hash ON Badges;
DROP INDEX idx_comments_text_hash ON Comments;
DROP INDEX idx_posttypes_type_hash ON PostTypes;
DROP INDEX idx_linktypes_type_hash ON LinkTypes;
DROP INDEX idx_postlinks_creationdate_hash ON PostLinks;
DROP INDEX idx_votetypes_name_hash ON VoteTypes;
DROP INDEX idx_votes_creationdate_hash ON Votes;
