CREATE OR REPLACE TABLE usuarios_hash AS
SELECT *
FROM Users;

CREATE OR REPLACE TABLE posts_hash AS
SELECT *
FROM Posts;

CREATE OR REPLACE TABLE badges_hash AS
SELECT *
FROM Badges;

CREATE OR REPLACE TABLE comments_hash AS
SELECT *
FROM Comments;

CREATE OR REPLACE TABLE posttypes_hash AS
SELECT *
FROM PostTypes;

CREATE OR REPLACE TABLE linktypes_hash AS
SELECT *
FROM LinkTypes;

CREATE OR REPLACE TABLE postlinks_hash AS
SELECT *
FROM PostLinks;

CREATE OR REPLACE TABLE votetypes_hash AS
SELECT *
FROM VoteTypes;

CREATE OR REPLACE TABLE votes_hash AS
SELECT *
FROM Votes;
