DROP TABLE IF EXISTS usuarios_for_update;
DROP TABLE IF EXISTS posts_for_update;
DROP TABLE IF EXISTS badges_for_update;
DROP TABLE IF EXISTS comments_for_update;
DROP TABLE IF EXISTS posttypes_for_update;
DROP TABLE IF EXISTS linktypes_for_update;
DROP TABLE IF EXISTS postlinks_for_update;
DROP TABLE IF EXISTS votetypes_for_update;
DROP TABLE IF EXISTS votes_for_update;
